runtime: java17
env: standard

instance_class: F1  # Clase de instancia gratuita
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  script: this field is required, but ignored
